apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-environments
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: MikeSydo
          repo: Preview-Environment-Service
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "preview-pr-{{number}}"
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
    spec:
      project: preview-project
      source:
        repoURL: "https://github.com/MikeSydo/Preview-Environment-Service.git"
        targetRevision: "{{head_sha}}"
        path: helm/preview-app
        helm:
          parameters:
            - name: image.repository
              value: "ghcr.io/mikesydo/preview-app"
            - name: image.tag
              value: "pr-{{number}}"
            - name: ingress.host
              value: "pr-{{number}}.18-185-231-49.nip.io"
            - name: ingress.port
              value: "30080"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "preview-pr-{{number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
